// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/smallMicro.proto

package smallMicro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SmallMicro service

func NewSmallMicroEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SmallMicro service

type SmallMicroService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (SmallMicro_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (SmallMicro_PingPongService, error)
}

type smallMicroService struct {
	c    client.Client
	name string
}

func NewSmallMicroService(name string, c client.Client) SmallMicroService {
	return &smallMicroService{
		c:    c,
		name: name,
	}
}

func (c *smallMicroService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SmallMicro.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smallMicroService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (SmallMicro_StreamService, error) {
	req := c.c.NewRequest(c.name, "SmallMicro.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &smallMicroServiceStream{stream}, nil
}

type SmallMicro_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type smallMicroServiceStream struct {
	stream client.Stream
}

func (x *smallMicroServiceStream) Close() error {
	return x.stream.Close()
}

func (x *smallMicroServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smallMicroServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smallMicroServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smallMicroServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smallMicroService) PingPong(ctx context.Context, opts ...client.CallOption) (SmallMicro_PingPongService, error) {
	req := c.c.NewRequest(c.name, "SmallMicro.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &smallMicroServicePingPong{stream}, nil
}

type SmallMicro_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type smallMicroServicePingPong struct {
	stream client.Stream
}

func (x *smallMicroServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *smallMicroServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *smallMicroServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smallMicroServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smallMicroServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *smallMicroServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SmallMicro service

type SmallMicroHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, SmallMicro_StreamStream) error
	PingPong(context.Context, SmallMicro_PingPongStream) error
}

func RegisterSmallMicroHandler(s server.Server, hdlr SmallMicroHandler, opts ...server.HandlerOption) error {
	type smallMicro interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type SmallMicro struct {
		smallMicro
	}
	h := &smallMicroHandler{hdlr}
	return s.Handle(s.NewHandler(&SmallMicro{h}, opts...))
}

type smallMicroHandler struct {
	SmallMicroHandler
}

func (h *smallMicroHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SmallMicroHandler.Call(ctx, in, out)
}

func (h *smallMicroHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SmallMicroHandler.Stream(ctx, m, &smallMicroStreamStream{stream})
}

type SmallMicro_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type smallMicroStreamStream struct {
	stream server.Stream
}

func (x *smallMicroStreamStream) Close() error {
	return x.stream.Close()
}

func (x *smallMicroStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smallMicroStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smallMicroStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smallMicroStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *smallMicroHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SmallMicroHandler.PingPong(ctx, &smallMicroPingPongStream{stream})
}

type SmallMicro_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type smallMicroPingPongStream struct {
	stream server.Stream
}

func (x *smallMicroPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *smallMicroPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *smallMicroPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *smallMicroPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *smallMicroPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *smallMicroPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
